# Generated by Django 4.0.6 on 2024-03-20 18:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('soundSafariApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(default=None, null=True)),
                ('picture', models.ImageField(upload_to='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.RenameField(
            model_name='album',
            old_name='duation',
            new_name='duration',
        ),
        migrations.AddField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='soundSafariApp.artist'),
        ),
        migrations.AddField(
            model_name='album',
            name='genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='soundSafariApp.genre'),
        ),
        migrations.AddField(
            model_name='album',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='page',
            name='album',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='soundSafariApp.album'),
        ),
        migrations.AddField(
            model_name='page',
            name='artist',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='soundSafariApp.artist'),
        ),
        migrations.AddField(
            model_name='page',
            name='song',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='soundSafariApp.song'),
        ),
        migrations.AddField(
            model_name='page',
            name='url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='soundSafariApp.page'),
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='song',
            name='album',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='soundSafariApp.album'),
        ),
        migrations.AddField(
            model_name='song',
            name='artist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='soundSafariApp.artist'),
        ),
        migrations.AddField(
            model_name='song',
            name='genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='soundSafariApp.genre'),
        ),
        migrations.AddField(
            model_name='song',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='release_date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='birthDate',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='genre',
            name='song_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='date_added',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='release_date',
            field=models.DateField(default=None, null=True),
        ),
    ]
