# Generated by Django 4.0.6 on 2024-03-20 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('soundSafariApp', '0002_userprofile_delete_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='soundSafariApp.userprofile'),
        ),
    ]
