# Generated by Django 4.0.6 on 2024-03-21 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('soundSafariApp', '0002_userprofile_delete_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='page',
        ),
        migrations.AddField(
            model_name='review',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='soundSafariApp.album'),
        ),
        migrations.AddField(
            model_name='review',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='soundSafariApp.artist'),
        ),
        migrations.AddField(
            model_name='review',
            name='song',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='soundSafariApp.song'),
        ),
        migrations.AlterField(
            model_name='song',
            name='album',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='soundSafariApp.album'),
        ),
        migrations.AlterField(
            model_name='song',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.DeleteModel(
            name='Page',
        ),
    ]
