# Generated by Django 4.0.6 on 2024-03-21 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soundSafariApp', '0004_alter_album_duration_alter_song_album_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='avg_rating',
            field=models.IntegerField(default=0),
        ),
    ]
