# Generated by Django 4.0.6 on 2024-03-21 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soundSafariApp', '0005_alter_page_avg_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='name',
            field=models.CharField(default='page', max_length=30),
        ),
    ]
