# Generated by Django 4.0.6 on 2024-03-22 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soundSafariApp', '0003_remove_review_page_review_album_review_artist_and_more'),
        ('soundSafariApp', '0006_page_name'),
    ]

    operations = [
    ]
