# Generated by Django 4.0.6 on 2024-03-22 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('soundSafariApp', '0007_merge_20240322_0228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='album',
        ),
        migrations.RemoveField(
            model_name='review',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='review',
            name='song',
        ),
        migrations.AlterField(
            model_name='song',
            name='album',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='soundSafariApp.album'),
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='page', max_length=30)),
                ('avg_rating', models.IntegerField(default=0)),
                ('url', models.URLField(null=True)),
                ('album', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='soundSafariApp.album')),
                ('artist', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='soundSafariApp.artist')),
                ('song', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='soundSafariApp.song')),
            ],
        ),
        migrations.AddField(
            model_name='review',
            name='page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='soundSafariApp.page'),
        ),
    ]
