# Generated by Django 4.0.6 on 2024-03-22 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soundSafariApp', '0009_alter_album_picture_alter_artist_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='picture',
            field=models.ImageField(upload_to='media/images/'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='picture',
            field=models.ImageField(upload_to='media/images/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(default='images/defaultUsrImg.jpg', upload_to=''),
        ),
    ]
