# Generated by Django 4.0.6 on 2024-03-22 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soundSafariApp', '0009_userprofile_bio'),
        ('soundSafariApp', '0010_alter_album_picture_alter_artist_picture_and_more'),
    ]

    operations = [
    ]
