# Generated by Django 4.2.11 on 2024-03-22 09:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("soundSafariApp", "0011_merge_20240322_0412"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="name",
            field=models.CharField(default="No Name", max_length=30),
        ),
    ]
