# Generated by Django 4.0.6 on 2024-03-22 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soundSafariApp', '0013_alter_review_date_added_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='pageName',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
