# Generated by Django 4.0.6 on 2024-03-22 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soundSafariApp', '0014_review_pagename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='pageName',
        ),
    ]
